runtime: go
api_version: go1

handlers:
- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)
  
- url: /(.*\.map)
  static_files: static/\1
  upload: static/(.*\.map)
 
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)
 
- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)
 
- url: /(.*\.xml)
  mime_type: application/xml
  static_files: static/\1
  upload: static/(.*\.xml)

- url: /(.*\.woff)
  static_files: static/\1
  upload: static/(.*\.woff)

- url: /(.*\.woff2)
  static_files: static/\1
  upload: static/(.*\.woff2)

- url: /(.*\.ttf)
  static_files: static/\1
  upload: static/(.*\.ttf)
  
- url: /(.*\.svg)
  static_files: static/\1
  upload: static/(.*\.svg)
  
- url: /(.*\.eot)
  static_files: static/\1
  upload: static/(.*\.eot)
  
- url: /(.*\.otf)
  static_files: static/\1
  upload: static/(.*\.otf)

# favicon
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# site root
- url: /
  script: _go_app
  
- url: /about.*
  script: _go_app

- url: /characters.*
  script: _go_app
  
- url: /phases.*
  script: _go_app
  
- url: /events.*
  script: _go_app
  
- url: /api.*
  script: _go_app